name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'  # Używamy konkretnej wersji Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Deploying with secret key..."
          echo "My secret key is $OPENAI_API_KEY"
          # Tutaj dodaj polecenie do wdrożenia aplikacji, np. uruchomienie serwera
          # Przykład:
          # python app.py
