name: CI/CD Workflow

on:
  push:
    branches:
      - master  # Użyj gałęzi 'main', jeśli to jest główna gałąź repozytorium

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'  # Używamy konkretnej wersji Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download pl_core_news_sm  # Instalacja modelu spaCy

      - name: Deploy
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          gunicorn --bind 0.0.0.0:8000 app:app
